legislature/urls.py
from django.conf.urls import patterns, url
from django.views.decorators.cache import cache_page

from legislature import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^about/donate/$', views.donate, name='donate'),
    url(r'^about/volunteer/$', views.volunteer, name='volunteer'),
    url(r'^people/$', views.people, name='speaker-list'),
    url(r'^people/(?P<slug>[-_\w]+)/$', views.person, name='speaker-view'),
    url(r'^people/(?P<slug>[-_\w]+)/notices/$', views.person_notices, name='speaker-view-notices'),
    url(r'^debates/$', views.debates, name='section-list'),
    url(r'^debates/(?P<year>\d{4})/$', views.debates_by_year, name='section-list-by-year'),
    url(r'^debates/(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.debates_by_month, name='section-list-by-month'),
    # It's possible for two hansards to have the same date, so we use slugs.
    url(r'^debates/(?P<slug>\D[-_\w]+)/$', views.debate, name='section-view'),
    url(r'^written-notices/(?P<slug>\D[-_\w]+)/$', views.notices, name='notices-view'),
    # OpenParliament.ca uses a `sequence` field to determine the page on which
    # the speech appers. SayIt lists all speeches in a section. Until SayIt adds
    # a `sequence` field to the Speech model, we put all speeches on one page
    # when linking to a speech.
    url(r'^debates/(?P<slug>\D[-_\w]+)/single-page/$', views.debate_single_page, name='section-view-single-page'),
    url(r'^written-notices/(?P<slug>\D[-_\w]+)/single-page/$', views.notices_single_page, name='notices-view-single-page'),
    url(r'^bills/$', cache_page(86400)(views.bills), name='bill-list'),
    url(r'^bills/(?P<slug>[-_\w.]+)/$', cache_page(86400)(views.bill), name='bill-view'),
    url(r'^search/', lambda request: views.CustomSearchView()(request), name='haystack_search'),
)

openhousens/urls.py
from django.conf.urls import patterns, include

urlpatterns = patterns('',
    (r'', include('legislature.urls', namespace='legislature', app_name='legislature')),
)

openhousens/templates/speeches/_breadcrumbs.html
{% load url from future %}
{% load legislature_extras %}

<ol class="breadcrumb">
  <li><a href="{% url 'legislature:home' %}">Home</a></li>
{% if section %}
  <li><a href="{% url 'legislature:section-list' %}">Debates</a></li>
  <li><a href="{% url 'legislature:section-list-by-year' year=section.start_date.year %}">{{ section.start_date.year }}</a></li>
  <li><a href="{% url 'legislature:section-list-by-month' year=section.start_date.year month=section.start_date.month %}">{{ section.start_date.month|month_name }}</a></li>
  <li class="active">{{ section.title }}</li>
{% elif month %}
  <li><a href="{% url 'legislature:section-list' %}">Debates</a></li>
  <li><a href="{% url 'legislature:section-list-by-year' year=month.year %}">{{ month.year }}</a></li>
  <li class="active">{{ month.month|month_name }}</li>
{% elif year %}
  <li><a href="{% url 'legislature:section-list' %}">Debates</a></li>
  <li class="active">{{ year.year }}</li>
{% elif speaker %}
  <li><a href="{% url 'legislature:speaker-list' %}">People</a></li>
  <li class="active">{{ speaker.name|person_name }}</li>
{% elif bill %}
  <li><a href="{% url 'legislature:bill-list' %}">Bills</a></li>
  <li class="active">Bill No. {{ bill.identifier }}</li>
{% elif speaker_list %}
  <li class="active">People</li>
{% elif latest %}
  <li class="active">Debates</li>
{% elif title %}
  <li class="active">{{ title }}</li>
{% elif object_list %}
  <li class="active">Bills</li>
{% elif query %}
  <li><a href="{% url 'legislature:haystack_search' %}">Search</a></li>
  <li class="active">{{ query }}</li>
{% else %}
  <li class="active">Search</li>
{% endif %}
</ol>

openhousens/templates/speeches/base.html
{% extends 'speeches/superbase.html' %}
{% load staticfiles %}

{% block facebook %}
<meta property="og:title" content="{% block title %}{% endblock %}">
<meta property="og:site_name" content="OpenHouseNS">
<meta property="og:image" content="http://www.openhousens.ca{% static 'img/facebook-share.png' %}">
{% endblock %}

openhousens/templates/speeches/section_detail.html
{% extends 'speeches/base.html' %}
{% load url from future %}

{% block title %}Debates of {{ section.start_date|date:"F jS, Y" }}{% endblock %}

{% block content %}
{% include "speeches/_breadcrumbs.html" %}

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-2">
      <h1>Debates of {{ section.start_date|date:"F jS, Y" }}</h1>

      <p>House of Assembly Hansard {{ section.number }} of the {{ section.legislature }}, {{ section.session }}. (The <a href="{{ section.source_url }}">original version</a> is on the legislature's site.)</p>
    </div>
  </div>

{% for speech in speeches %}
  <div class="row">
    <div class="col-xs-2">
  {% if speech.section.parent.parent_id %}
      <div class="heading-level-1">{{ speech.section.parent.title }}</div>
      <div class="heading-level-2">{{ speech.section.title }}</div>
  {% elif speech.section.parent_id %}
      <div class="heading-level-1">{{ speech.section.title }}</div>
  {% endif %}
    </div>
    <div class="col-xs-10" id="s{{ speech.id }}" class="{% if speech.speaker %}{% else %}{% endif %}"{% if speech.speaker.colour %} style="border-left-color: #{{ speech.speaker.colour }};"{% endif %}>
{% include "speeches/speech.html" with speech=speech nosection="1" section=section noli=1 %}
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

openhousens/templates/speeches/speech.html
{% load firstof url from future %}
{% load legislature_extras staticfiles highlight speech_utils %}

{% if full %}
  {% if speech.speaker_display %}
    {% if speech.speaker.image %}
<div class="image">
  <a href="{% url 'legislature:speaker-view' speech.speaker.slug %}">
    <div class="avatar" style="background-image: url({{ speech.speaker.image }})"></div>
  </a>
</div>
    {% endif %}
<p class="from">
    {% if speech.speaker_id %}
  <a href="{% url 'legislature:speaker-view' speech.speaker.slug %}">{{ speech|speech_speaker }}</a>
      {% if speech.speaker.memberships.all %}
  <span class="swatch {{ speech.speaker|speaker_party_class }}"></span>
  <span class="memberships">{{ speech.speaker|speaker_description }}</span>
      {% endif %}
    {% else %}
  {{ speech|speech_speaker }}
    {% endif %}
</p>
  {% endif %}
{% else %}
<p class="context">
  <span class="title">
    <a href="{{ speech.section|single_page_hansard_url }}#s{{ speech.id }}">{% if speech.title or speech.section.parent_id %}{% firstof speech.title|heading speech.section.title|heading %}{% else %}Debates{% endif %}</a>
  </span>
  on
  <span class="date">
    <a href="{{ speech.section|hansard_url }}">{{ speech.section.start_date|date:"F jS, Y" }}</a>
  </span>
  {% if query %}
    {% if speech.speaker_display %}
  by
  <span class="from">
      {% if speech.speaker_id %}
    <a href="{% url 'legislature:speaker-view' speech.speaker.slug %}">{{ speech|speech_speaker }}</a>
      {% else %}
    {{ speech|speech_speaker }}
      {% endif %}
  </span>
    {% endif %}
  {% endif %}
</p>
{% endif %}
 
<div class="speech">
{% if query %}
  <div class="highlighted">
{% highlight result.text with query css_class "" html_tag "em" max_length 400 %}
  </div>
{% elif truncate %}
  <div class="truncated">
{{ speech.text|bleach|truncatewords_html:"50" }}
  </div>
{% else %}
{{ speech.text|bleach }}
{% endif %}
</div>

{% if full and speech.speaker_display %}
<div class="actions">
  <a href="#s{{ speech.id }}" class="link">
    <span class="glyphicon glyphicon-link"></span> Link
  </a>
  <a href="https://twitter.com/share?related=OpenHouseNS%3Aopenhousens.ca&amp;url={{ request.build_absolute_uri|urlencode }}%23s{{speech.id}}&amp;text={{ speech|tweet_text }}&amp;via=OpenHouseNS" class="twitter">
    <img src="{% static 'img/twitter.png' %}" width="20" height="16" alt=""> Tweet
  </a>
</div>
{% endif %}

openhousens/templates/speeches/superbase.html
{% load url from future %}{% load staticfiles %}<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% block title %}{% endblock %} - OpenHouseNS</title>
{% block facebook %}{% endblock %}
<meta name="description" content="Easily track what's said in the Nova Scotia Legislature">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
{% block head %}{% endblock %}
</head>
<body>

<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <img src="{% static 'img/logo.png' %}" width="126" height="43" alt="OpenHouseNS">
      </span>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'legislature:home' %}">Home Page</a></li>
        <li><a href="{% url 'legislature:speaker-list' %}">People</a></li>
        <li><a href="{% url 'legislature:section-list' %}">Debates</a></li>
        <li><a href="{% url 'legislature:bill-list' %}">Bills</a></li>
        <li><a href="{% url 'legislature:donate' %}">Donate</a></li>
        <li><a href="{% url 'legislature:volunteer' %}">Volunteer</a></li>
        <li><a href="{% url 'legislature:about' %}">About</a></li>
      </ul>
      <form action="{% url 'legislature:haystack_search' %}" method="get" class="navbar-form navbar-right" role="search">
        <input name="q" type="text" class="form-control" placeholder="Search">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
      </form>
    </div>
  </div>
</nav>

{% block content %}{% endblock %}

<footer>
  <p>An unofficial record of the proceedings of the Nova Scotia House of Assembly</p>
 <p>Follow <a href="http://twitter.com/openhousens">@OpenHouseNS on Twitter</a> for daily updates when the House is in session.</p>
  <p class="latest"> Help keep OpenHouseNS <i>open</i>: <a href="{% url 'legislature:donate' %}"><strong>make a small donation</strong></a> to keep this site running</a>.</p>
  <p>Brought to you by:<img src="{% static 'img/springtide-collective.png' %}" alt="" height="25" width="25"> <a href="http://www.springtidecollective.ca/"><strong>Springtide Collective</strong></a> & <img src="{% static 'img/open-north-symbol.png' %}" alt="" height="25" width="25"> <a href="http://www.opennorth.ca/"><strong>Open North</strong></a>.</p>

</footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js"></script>
<script src="{% static 'js/d3.layout.cloud.js' %}"></script>
{% block js %}{% endblock %}
<script src="{% static 'js/main.js' %}"></script>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-52754755-1', 'auto');
ga('send', 'pageview');
</script>

</body>
</html>