legislature/urls.py
from django.conf.urls import patterns, url
from django.views.decorators.cache import cache_page

from legislature import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^about/donate/$', views.donate, name='donate'),
    url(r'^about/volunteer/$', views.volunteer, name='volunteer'),
    url(r'^people/$', views.people, name='speaker-list'),
    url(r'^people/(?P<slug>[-_\w]+)/$', views.person, name='speaker-view'),
    url(r'^people/(?P<slug>[-_\w]+)/notices/$', views.person_notices, name='speaker-view-notices'),
    url(r'^debates/$', views.debates, name='section-list'),
    url(r'^debates/(?P<year>\d{4})/$', views.debates_by_year, name='section-list-by-year'),
    url(r'^debates/(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.debates_by_month, name='section-list-by-month'),
    # It's possible for two hansards to have the same date, so we use slugs.
    url(r'^debates/(?P<slug>\D[-_\w]+)/$', views.debate, name='section-view'),
    url(r'^written-notices/(?P<slug>\D[-_\w]+)/$', views.notices, name='notices-view'),
    # OpenParliament.ca uses a `sequence` field to determine the page on which
    # the speech appers. SayIt lists all speeches in a section. Until SayIt adds
    # a `sequence` field to the Speech model, we put all speeches on one page
    # when linking to a speech.
    url(r'^debates/(?P<slug>\D[-_\w]+)/single-page/$', views.debate_single_page, name='section-view-single-page'),
    url(r'^written-notices/(?P<slug>\D[-_\w]+)/single-page/$', views.notices_single_page, name='notices-view-single-page'),
    url(r'^bills/$', cache_page(86400)(views.bills), name='bill-list'),
    url(r'^bills/(?P<slug>[-_\w.]+)/$', cache_page(86400)(views.bill), name='bill-view'),
    url(r'^search/', lambda request: views.CustomSearchView()(request), name='haystack_search'),
)

openhousens/urls.py
from django.conf.urls import patterns, include

urlpatterns = patterns('',
    (r'', include('legislature.urls', namespace='legislature', app_name='legislature')),
)

legislature/models.py
# coding: utf-8
import os
import re

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from speeches.models import Speaker
from twitter import OAuth, Twitter

twitter = Twitter(auth=OAuth(
    token=os.getenv('TWITTER_ACCESS_TOKEN'),
    token_secret=os.getenv('TWITTER_TOKEN_SECRET'),
    consumer_key=os.getenv('TWITTER_CONSUMER_KEY'),
    consumer_secret=os.getenv('TWITTER_CONSUMER_SECRET'),
))


@python_2_unicode_compatible
class Bill(models.Model):
    STATUS_CHOICES = (
        ('1st', 'First Reading'),
        ('2nd', 'Second Reading'),
        ('LA', 'Law Amendments Committee'),
        ('PL', 'Private & Local Bills Committee'),
        ('WH', 'Committee of the Whole House'),
        ('3rd', 'Third Reading'),
        ('RA', 'Royal Assent'),
    )

    identifier = models.PositiveIntegerField()
    title = models.TextField()
    description = models.TextField()
    classification = models.TextField()
    creator = models.ForeignKey(Speaker, blank=True, null=True, on_delete=models.SET_NULL)
    modified = models.DateField()
    status = models.CharField(max_length=3, choices=STATUS_CHOICES)
    slug = models.TextField()
    url = models.URLField()
    law_amendments_committee_submissions_url = models.URLField()

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('legislature:bill-view', (), {'slug': self.slug})


@python_2_unicode_compatible
class Action(models.Model):
    description = models.TextField()
    date = models.DateField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    bill = models.ForeignKey(Bill, blank=True, null=True)  # had to be NULL for migration

    class Meta:
        ordering = ['date']
        unique_together = ('bill', 'description')

    def __str__(self):
        return self.description


@receiver(post_save, sender=Action)
def tweet_bill_status(sender, instance, created, **kwargs):
    # @note Disable Twitter when scraping bills for the first time.
    if created and os.getenv('TWITTER_CONSUMER_SECRET', False):
        if instance.bill.status == '1st':
            text = 'The {title} was introduced {url}'
        if instance.bill.status == '2nd':
            text = 'The House voted on referring the {title} to committee {url}'
        elif instance.bill.status == 'LA' or instance.bill.status == 'PL':
            text = 'A committee considered the {title} {url}'
        elif instance.bill.status == 'WH':
            text = 'The House debated the {title} {url}'
        elif instance.bill.status == '3rd':
            text = 'The House voted on passing the {title} {url}'
        elif instance.bill.status == 'RA':
            text = 'The {title} became law {url}'

        title = instance.bill.title
        title = re.sub(r'\s+', ' ', title)
        title = re.sub(r'\AAn ', '', title)
        title = re.sub(r' \([Aa]mended\)', '', title)

        # Accounts for "{title}" (7) and 22-character "{url}" (5).
        # @see https://dev.twitter.com/rest/reference/get/help/configuration
        title_maxlength = 130 - len(text)
        if len(title) > title_maxlength:
            title = title[:title_maxlength - 1] + '…'

        twitter.statuses.update(status=text.format(title=title, url='http://www.openhousens.ca%s' % instance.bill.get_absolute_url()))

legislature/views.py
import calendar
import json
import re
from collections import defaultdict
from heapq import nlargest
from operator import itemgetter

from django import forms
from django.db.models import Count
from django.shortcuts import get_object_or_404, render_to_response
from django.utils.html import strip_tags
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from haystack.forms import SearchForm
from haystack.query import RelatedSearchQuerySet
from haystack.views import SearchView
from popolo.models import Organization
from speeches.models import Section, Speaker, Speech
from speeches.search import SpeakerForm

from legislature.models import Action, Bill

STOPWORDS = frozenset([
    # nltk.corpus.stopwords.words('english')
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your',
    'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her',
    'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs',
    'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those',
    'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had',
    'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if',
    'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with',
    'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after',
    'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over',
    'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where',
    'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other',
    'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too',
    'very', 's', 't', 'can', 'will', 'just', 'don', 'should', 'now',
    # @see https://github.com/rhymeswithcycle/openparliament/blob/master/parliament/text_analysis/frequencymodel.py
    "it's", "we're", "we'll", "they're", "can't", "won't", "isn't", "don't", "he's",
    "she's", "i'm", "aren't", "government", "house", "committee", "would", "speaker",
    "motion", "mr", "mrs", "ms", "member", "minister", "canada", "members", "time",
    "prime", "one", "parliament", "us", "bill", "act", "like", "canadians", "people",
    "said", "want", "could", "issue", "today", "hon", "order", "party", "canadian",
    "think", "also", "new", "get", "many", "say", "look", "country", "legislation",
    "law", "department", "two", "day", "days", "madam", "must", "that's", "okay",
    "thank", "really", "much", "there's", "yes", "no",
    # HTML tags
    'sup',
    # Nova Scotia
    "nova", "scotia", "scotians", "province", "honourable", "premier",
    # artifacts
    "\ufffd", "n't",
])

r_punctuation = re.compile(r"[^\s\w0-9'’—-]", re.UNICODE)
r_whitespace = re.compile(r'[\s—]+')

def home(request):
    hansard = Section.objects.filter(parent=None).order_by('-start_date').first()

    # Get the latest hansard's speeches as in DebateDetailView.
    section_ids = []
    for section in hansard._get_descendants(include_self=True):
        if section.title != 'NOTICES OF MOTION UNDER RULE 32(3)':
            section_ids.append(section.id)
    speeches = Speech.objects.filter(section__in=section_ids)

    # @see https://github.com/rhymeswithcycle/openparliament/blob/master/parliament/text_analysis/analyze.py
    # @see https://github.com/rhymeswithcycle/openparliament/blob/master/parliament/text_analysis/frequencymodel.py

    # Get the counts of all non-stopwords.
    word_counts = defaultdict(int)
    total_count = 0

    for speech in speeches:
        for word in r_whitespace.split(r_punctuation.sub(' ', strip_tags(speech.text).lower())):
            if word not in STOPWORDS and len(word) > 2:
                word_counts[word] += 1
                total_count += 1

    word_counts = {word: count for word, count in word_counts.items()}
    most_common_words = nlargest(50, word_counts.items(), key=itemgetter(1))

    return render_to_response('home.html', {
        'hansard': hansard,
        'most_common_words': json.dumps(most_common_words),
    })


def about(request):
    return render_to_response('about.html', {'title': 'About'})


def donate(request):
    return render_to_response('donate.html', {'title': 'Donate'})


def volunteer(request):
    return render_to_response('volunteer.html', {'title': 'Volunteer'})


class TitleAdder(object):
    def get_context_data(self, **kwargs):
        context = super(TitleAdder, self).get_context_data(**kwargs)
        context.update(title=self.page_title)
        return context


class DebateArchiveIndexView(ArchiveIndexView):
    queryset = Section.objects.filter(parent=None)
    date_field = 'start_date'
    template_name = 'section_archive.html'
debates = DebateArchiveIndexView.as_view()


class DebateYearArchiveView(TitleAdder, YearArchiveView):
    queryset = Section.objects.filter(parent=None).order_by('start_date')
    date_field = 'start_date'
    template_name = 'section_archive_year.html'
    make_object_list = True
    page_title = lambda self: 'Debates from %s' % self.get_year()
debates_by_year = DebateYearArchiveView.as_view()


class DebateMonthArchiveView(TitleAdder, MonthArchiveView):
    queryset = Section.objects.filter(parent=None).order_by('start_date')
    date_field = 'start_date'
    template_name = 'section_archive_month.html'
    make_object_list = True
    page_title = lambda self: 'Debates from %s %s' % (calendar.month_name[int(self.get_month())], self.get_year())
    month_format = '%m'  # Use integers in paths.
debates_by_month = DebateMonthArchiveView.as_view()


class SpeakerListView(ListView):
    queryset = Speaker.objects.exclude(email=None).order_by('sort_name').prefetch_related('memberships')
    template_name = 'speaker_list.html'

    def get_context_data(self, **kwargs):
        context = super(SpeakerListView, self).get_context_data(**kwargs)
        context['memberships_counts'] = Organization.objects.filter(classification='political party').annotate(memberships_count=Count('memberships')).order_by('-memberships_count').prefetch_related('other_names')
        context['former_list'] = sorted(Speaker.objects.filter(email=None), key=lambda v: v.name.split(' ')[-1].lower())
        return context
people = SpeakerListView.as_view()


class SpeakerDetailView(ListView):
    paginate_by = 15
    template_name = 'speaker_detail.html'
    notices = False

    def get_queryset(self):
        self.object = get_object_or_404(Speaker, slugs__slug=self.kwargs.get('slug', None))
        qs = self.object.speech_set.order_by('-start_date', '-id').select_related('section', 'section__parent', 'section__parent__parent')
        if self.notices:
            qs = qs.filter(section__heading='NOTICES OF MOTION UNDER RULE 32(3)')
        else:
            qs = qs.exclude(section__heading='NOTICES OF MOTION UNDER RULE 32(3)')
        return qs

    def get_context_data(self, **kwargs):
        context = super(SpeakerDetailView, self).get_context_data(**kwargs)
        context['speaker'] = self.object
        context['notices'] = self.notices
        return context
person = SpeakerDetailView.as_view()
person_notices = SpeakerDetailView.as_view(notices=True)


class DebateDetailView(ListView):
    paginate_by = 15
    template_name = 'section_detail.html'
    notices = False

    # @see http://ccbv.co.uk/projects/Django/1.6/django.views.generic.list/ListView/
    # @see http://ccbv.co.uk/projects/Django/1.6/django.views.generic.detail/DetailView/
    # @see https://docs.djangoproject.com/en/1.4/topics/class-based-views/#dynamic-filtering
    def get_queryset(self):
        self.object = get_object_or_404(Section, parent_id=None, slug=self.kwargs.get('slug', None))
        self.notices_present = False
        section_ids = []
        for section in self.object._get_descendants(include_self=True):
            if section.title == 'NOTICES OF MOTION UNDER RULE 32(3)':
                self.notices_present = True
                if self.notices:
                    section_ids.append(section.id)
            elif not self.notices:
                section_ids.append(section.id)
        return Speech.objects.filter(section__in=section_ids).prefetch_related('speaker', 'speaker__memberships', 'speaker__memberships__organization', 'section', 'section__parent')

    def get_context_data(self, **kwargs):
        context = super(DebateDetailView, self).get_context_data(**kwargs)
        context['section'] = self.object
        context['notices'] = self.notices
        context['notices_present'] = self.notices_present
        return context
debate = DebateDetailView.as_view()
notices = DebateDetailView.as_view(notices=True)
debate_single_page = DebateDetailView.as_view(paginate_by=None)
notices_single_page = DebateDetailView.as_view(paginate_by=None, notices=True)


class BillListView(ListView):
    model = Bill
    template_name = 'bill_list.html'
bills = BillListView.as_view()


class BillDetailView(DetailView):
    model = Bill
    template_name = 'bill_detail.html'
bill = BillDetailView.as_view()


# @see http://django-haystack.readthedocs.org/en/latest/views_and_forms.html#creating-your-own-form
# @see https://github.com/toastdriven/django-haystack/blob/master/haystack/forms.py
class SpeechForm(SearchForm):
    """
    A form with a hidden integer field that searches the speaker ID field
    """
    p = forms.IntegerField(required=False, widget=forms.HiddenInput())
    speaker = None  # the speaker object

    def __init__(self, *args, **kwargs):
        if kwargs.get('searchqueryset') is None:
            kwargs['searchqueryset'] = RelatedSearchQuerySet()
        super(SpeechForm, self).__init__(*args, **kwargs)

    # @see http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html
    # @see http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html#SearchQuerySet.auto_query

legislature/templates/bill_detail.html
{% extends 'speeches/base.html' %}
{% load url from future %}
{% load staticfiles legislature_extras %}

{% block title %}Bill No. {{ bill.identifier }} {{ bill.title }}{% endblock %}

{% block head %}
<link rel="alternate" type="application/rss+xml" href="http://nslegislature.ca/index.php/proceedings/rss_2.0/{{ bill.slug }}">
{% endblock %}

{% block content %}
{% include 'speeches/_breadcrumbs.html' %}

<div class="container-fluid" itemscope itemtype="http://schema.org/CreativeWork">
  <div class="row">
    <div class="col-sm-10 col-md-8 col-sm-offset-2">
      <header>
        <h1 itemprop="name">Bill No. {{ bill.identifier }}</h1>
        <p class="title" itemprop="alternateName">{{ bill.title }}</p>
{% if bill.description %}
        <p class="subtitle" itemprop="description">{{ bill.description }}</p>
{% endif %}
        <p>
          Subscribe to this <a href="http://nslegislature.ca/index.php/proceedings/rss_2.0/{{ bill.slug }}">RSS feed</a> to track changes to the bill's status.
{% if bill.classification == 'Public Bills' %}
          This is a <a href="http://nslegislature.ca/index.php/proceedings/types-of-bills/" target="_blank">public bill</a>, meaning it applies to the whole province and all its citizens. Public bills are either introduced by the government's cabinet ministers as government bills or by members as private members' bills.
{% elif bill.classification == 'Private and Local Bills' %}
          This is a <a href="http://nslegislature.ca/index.php/proceedings/types-of-bills/" target="_blank">private or local bill</a>, meaning it applies to only part of the province or only some of its citizens and corporations.
{% endif %}
          (The <a itemprop="url" href="{{ bill.url }}">original version</a> is on the legislature's site.)
        </p>
      </header>
    </div>
  </div>

{% if bill.creator %}
  <div class="row push-down">
    <div class="col-sm-2">
      <h2>Sponsor</h2>
    </div>
    <div class="col-sm-10 col-md-8" itemprop="creator" itemscope itemtype="http://schema.org/Person">
      <a href="{% url 'legislature:speaker-view' bill.creator.slug %}">
        <strong itemprop="name">{{ bill.creator.name|person_name }}</strong>
      </a>
      <span class="swatch {{ bill.creator|speaker_party_class }}" title="{{ bill.creator|speaker_party_name }}"></span>
    </div>
  </div>
{% endif %}

  <div class="row push-down">
    <div class="col-sm-2">
      <h2>Updates</h2>
    </div>
    <div class="col-sm-10 col-md-8">
      <dl class="dl-horizontal">
{% for action in bill.action_set.all %}
  {% if action.description != "Meeting Date(s)" %}
        <dt{{ action.description|bill_action_html_attributes }}>
          {{ action.description }}
        </dt>
        <dd>
    {% if action.description == "Law Amendments Committee" %}
          <a href="{{ bill.law_amendments_committee_submissions_url }}" target="_blank">Public input <span class="glyphicon glyphicon-new-window"></span></a>
    {% elif action.text %}
          {{ action.text }}
    {% elif action.description == "Commencement" %}
          {{ action.date|date:"F j, Y" }}
    {% else %}
          <a href="{% url 'legislature:haystack_search' %}?q=Bill%20{{ bill.identifier }}%20start_date%3A{{ action.date|date:"Y-m-d" }}">{{ action.date|date:"F j, Y" }}</a>
    {% endif %}
        </dd>
  {% endif %}
{% endfor %}
      </dl>
    </div>
  </div>
{% endblock %}

legislature/templates/home.html
{% extends 'speeches/base.html' %}
{% load url from future %}

{% block title %}Your Window into Province House{% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container-fluid">
    <h1>Easily track what's said in Nova Scotia's Legislature</h1>
  </div>
</div>

<div class="container-fluid home">
  <p class="lead">Important decisions are made in our legislature.</p>
  <p class="lead">We make it easy for Nova Scotians to know what's happening.</p>

  <form action="{% url 'legislature:haystack_search' %}" method="get" class="form-inline" role="form">
    <div class="form-group form-group-lg">
      <label class="sr-only" for="q">Enter a bill, keyword or name</label>
      <input name="q" id="q" type="search" class="form-control input-lg" placeholder="Enter a bill, keyword or name">
    </div>
    <button type="submit" class="btn btn-default btn-lg">Search</button>
  </form>

  <p class="latest"> Help keep OpenHouseNS <i>open</i>: <a href="{% url 'legislature:donate' %}"><strong>make a small donation</strong></a> to keep this site running</a></p>

{% if hansard %}
  <p class="latest">The latest transcript is from:  <a href="{% url 'legislature:section-view' hansard.slug %}"><strong>{{ hansard.start_date }}</strong></a></p>
{% endif %}

<script>var most_common_words = {{ most_common_words | safe }};</script>
<div class="wordcloud"></div>
</div>
{% endblock %}

legislature/templates/section_detail.html
{% extends 'speeches/base.html' %}
{% load url from future %}
{% load legislature_extras pagination %}

{% block title %}{% if notices %}Written Notices{% else %}Debates{% endif %} of {{ section.start_date|date:"F jS, Y" }}{% endblock %}

{% block content %}
{% include 'speeches/_breadcrumbs.html' %}
{% long_paginator as pagination %}

<div class="container-fluid" itemscope itemtype="http://schema.org/CreativeWork">
  <div class="row">
    <div class="col-sm-10 col-md-8 col-sm-offset-2">
      <h1>
        {% if notices %}Written Notices{% else %}Debates{% endif %} of
        <time itemprop="dateCreated" datetime="{{ section.start_date|date:"Y-m-d" }}">
          {{ section.start_date|date:"F jS, Y" }}
        </time>
      </h1>

      <p>
{% if notices %}
        Under <a href="http://nslegislature.ca/legc/rules.htm" target="_blank">Rule 32(3)</a> of the House of Assembly, member may give written notices of motions for resolutions before a meeting.
{% else %}
        House of Assembly Hansard {{ section.number }} of the {{ section.legislature }}, {{ section.session }}.
{% endif %}
        (The <a itemprop="url" href="{{ section.source_url }}">original version</a> is on the legislature's site.)
{% if notices_present %}
  {% if notices %}
        Read the <a href="{% url 'legislature:section-view' section.slug %}">debates of {{ section.start_date|date:"F jS, Y" }}</a>.
  {% else %}
        Read the <a href="{% url 'legislature:notices-view' section.slug %}">written notices of motions for resolutions</a> submitted before this meeting.
  {% endif %}
{% endif %}
      </p>
    </div>
  </div>


  <div class="row hidden-xs">
    <div class="col-sm-10 col-md-8 col-sm-offset-2">
{{ pagination }}
    </div>
  </div>

  <div class="speeches">
{% for speech in object_list %}
    <div class="row row-speech {{ speech|speech_class }}"{% ifchanged speech.section_id %} id="ss{{ speech.section_id }}"{% endifchanged %}>
      <div class="col-sm-2 col-meta hidden-xs">
  {% if speech.speaker_display %}
    {% if speech.section.parent.parent_id %}
        <div class="heading-level-1">{{ speech.section.parent.title|heading }}</div>
        <div class="heading-level-2">{{ speech.section.title|heading }}</div>
      {% if speech.title %}
        <div class="heading-level-3">{{ speech.title|heading }}</div>
      {% endif %}
    {% elif speech.section.parent_id %}
        <div class="heading-level-1">{{ speech.section.title|heading }}</div>
      {% if speech.title %}
        <div class="heading-level-2">{{ speech.title|heading }}</div>
      {% endif %}
    {% endif %}
  {% endif %}
      </div>
      <div class="col-sm-10 col-speech" id="s{{ speech.id }}">
        <div class="truncatable">
{% include 'speeches/speech.html' with speech=speech full=1 %}
        </div>
      </div>
    </div>
{% endfor %}
  </div>

  <div class="row">
    <div class="col-sm-10 col-md-8 col-sm-offset-2">
{{ pagination }}
    </div>
  </div>
</div>
{% endblock %}

legislature/templates/section_list.html
{% extends 'speeches/base.html' %}
{% load url from future %}

{% block title %}Debates{% endblock %}

{% block content %}
{% include "speeches/_breadcrumbs.html" %}

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-10 col-md-8 col-xs-offset-2">
      <h1>The Debates of the House of Assembly</h1>

      <p>When the House is in session, every word spoken by a member is faithfully transcribed and published in a document called a <a href="http://en.wikipedia.org/wiki/Hansard">Hansard</a>. We've made the transcripts since October 31, 2011 easily searchable and browseable. If you need to go further back, consult the <a href="http://nslegislature.ca/index.php/proceedings/hansard/">website of the Nova Scotia Legislature</a>.</p>

      <form action="{% url 'legislature:haystack_search' %}" method="get">
        <input type="search" name="q" placeholder="Enter a bill, keyword, phrase or name">
        <input type="submit" value="Search">
      </form>
    </div>
  </div>

  <div class="row push-down">
    <div class="col-xs-2">
      <h2>Recent</h2>
    </div>
    <div class="col-xs-10 col-md-8">
      <ul class="list-inline">
        {% for hansard in latest|slice:":16" %}<li>
          <a href="{% url 'legislature:section-view' hansard.slug %}">{{ hansard.start_date|date:"F jS" }}</a>
        </li>{% endfor %}
      </ul>
    </div>
  </div>

  <div class="row push-down">
    <div class="col-xs-2">
      <h2>Past</h2>
    </div>
    <div class="col-xs-10 col-md-8">
      <ul class="list-inline">
        {% for year in date_list %}<li>
          <a href="{% url 'legislature:section-list-by-year' year=year.year %}">{{ year.year }}</a>
        </li>{% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

legislature/templates/speaker_detail.html
{% extends 'speeches/base.html' %}
{% load url from future %}
{% load legislature_extras pagination %}

{% block title %}{{ speaker.name|person_name }}{% endblock %}

{% block content %}
{% include 'speeches/_breadcrumbs.html' %}
{% long_paginator as pagination %}

<div class="container-fluid speaker-detail" itemscope itemtype="http://schema.org/Person">
  <div class="row">
    <div class="col-sm-10 col-md-8 col-sm-offset-2">
      <h1 itemprop="name">{{ speaker.name|person_name }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
{% if speaker.image %}
      <figure>
        <img itemprop="image" src="{{ speaker.image }}" alt="">
        <figcaption>Nova Scotia Legislature photo</figcaption>
      </figure>
{% endif %}
{% if speaker.email %}
      <p class="contact">
        <a itemprop="email" href="mailto:{{ speaker.email }}">
          Email {{ speaker.name|person_short_name }}
        </a>
      </p>
{% endif %}
{% if speaker.sources.all %}
      <p class="hidden-xs">
        <a itemprop="url" href="{{ speaker.sources.all.0.url }}">
          On the legislature's site
        </a>
      </p>
{% endif %}
    </div>
    <div class="col-sm-10 col-md-8">
{% if speaker.memberships.all %}
      <p class="memberships">{{ speaker|speaker_description }}</p>
{% endif %}

      <form action="{% url 'legislature:haystack_search' %}" method="get" class="form-inline form-inline-always" role="form">
        <div class="form-group">
          <label class="sr-only" for="q">Enter a bill, keyword or name</label>
          <input name="q" id="q" type="search" class="form-control" placeholder="Search {{ speaker.name|person_short_name }}'s speeches">
        </div>
        <button type="submit" class="btn btn-default">
          <span class="hidden-xs">Search</span>
          <span class="visible-xs-inline">
            <span class="glyphicon glyphicon-search"></span>
          </span>
        </button>
        <input type="hidden" name="p" value="{{ speaker.id }}">
      </form>

      <ul class="nav nav-pills">
{% if notices %}
        <li>
          <a href="{% url 'legislature:speaker-view' speaker.slug %}">Speeches</a>
        </li>
        <li class="active">
          <span>Written notices</span>
        </li>
{% else %}
        <li class="active">
          <span>Speeches</span>
        </li>
        <li>
          <a href="{% url 'legislature:speaker-view-notices' speaker.slug %}">Written notices</a>
        </li>
{% endif %}
      </ul>

      <div class="hidden-xs">
{{ pagination }}
      </div>

{% for speech in object_list %}
      <div class="col-speech col-speech-with-border">
{% include 'speeches/speech.html' with speech=speech truncate=1 %}
      </div>
{% empty %}
      <p class="empty">No {% if notices %}written notices{% else %}speeches{% endif %}</p>
{% endfor %}

{{ pagination }}
    </div>
  </div>
</div>
{% endblock %}